apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: shasi-technologies
spec:
  template:
    spec:
      containers:
        - image: docker.io/shasidhar19/shasi-technologies:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
